name: Daily Tweet

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: npm start
        env:
          TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
          TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GTOKEN: ${{ secrets.GTOKEN }}
          MONGODB_URI: ${{secrets.MONGODB_URI}}
